### ISSUE TITLE
How to use this sampler? Sampler name not showing in jmeter

### ISSUE THREAD

**Issue by aedahh** [avisi/jmeter-mllp-tcpclient#1]
Hello,
I have downloaded this plugin, copied mllptcpsampler-1.0-SNAPSHOT.jar to apache-jmeter-2.11\lib\ext, then started up jmeter, when add sampler from Jmeter Thread Group, I don't see any new sampler name relating to mlptcpsampler.

How to use this plugin?
Thanks!

**Comment by rkettelerij** [comment]
I've added some documentation to the README file, see https://github.com/avisi/jmeter-mllp-tcpclient. 
This should clarify things for you. Let me know how it works out.

**Comment by aedahh** [comment]
Hello Richard,
Thanks for posting the details usage instruction, it is very helpful.

Don't know why it is not working for me. I am getting error:
"Response code: 500
Response message: Protocol handler not found."

If I removed the nl.avisi.jmeter.mllsampler.MllpTCPClient as Tcp client classname, then will get error:
"Response code: 500
Response message: org.apache.jmeter.protocol.tcp.sampler.ReadException: "
But I could received some data at receiver end (using HAPI TestPanel).

**Comment by rkettelerij** [comment]
There was a typo in the README. You should change the classname to `nl.avisi.jmeter.mllpsampler.MllpTCPClient` (note the 'p' in mllp)

**Comment by aedahh** [comment]
Thanks for the update. It works now.
